// <auto-generated />
using System;
using AkilliSehir.DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AkilliSehir.DataAccess.Migrations
{
    [DbContext(typeof(CityDbContext))]
    [Migration("20260803082407_VatandasTakipDuyuruVeRandevu")]
    partial class VatandasTakipDuyuruVeRandevu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AkilliSehir.Core.Entities.Ariza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Aciliyet")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ArizaTuru")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Bilinmiyor");

                    b.Property<int?>("AtananPersonelId")
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("BildirimiYapanVatandasId")
                        .HasColumnType("int");

                    b.Property<double>("Boylam")
                        .HasColumnType("float");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("Enlem")
                        .HasColumnType("float");

                    b.Property<string>("FotografUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("VatandasSecilenBirim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("YapayZekaGerekcesi")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("YapayZekaGuvenSkoru")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal(4,3)");

                    b.Property<string>("YonlendirilenBirim")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Diger");

                    b.HasKey("Id");

                    b.HasIndex("AtananPersonelId");

                    b.HasIndex("BildirimiYapanVatandasId", "KayitTarihi");

                    b.HasIndex("YonlendirilenBirim", "Durum");

                    b.ToTable("Arizalar", (string)null);
                });

            modelBuilder.Entity("AkilliSehir.Core.Entities.Duyuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("nvarchar(1600)");

                    b.Property<int>("KapsamYaricapiMetre")
                        .HasColumnType("int");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("KonumBoylam")
                        .HasColumnType("float");

                    b.Property<double?>("KonumEnlem")
                        .HasColumnType("float");

                    b.Property<string>("Oncelik")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("YayinBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YayinBitisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AktifMi", "YayinBaslangicTarihi");

                    b.ToTable("Duyurular", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AktifMi = true,
                            Baslik = "Planlı su bakım çalışması",
                            Icerik = "Seyhan çevresinde gece saatlerinde basınç düşüşü yaşanabilir. Ekipler bakım çalışmalarını sabah tamamlayacaktır.",
                            KapsamYaricapiMetre = 8000,
                            Kategori = "SuKesintisi",
                            KonumBoylam = 35.321300000000001,
                            KonumEnlem = 37.0,
                            Oncelik = "Onemli",
                            YayinBaslangicTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YayinBitisTarihi = new DateTime(2030, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AktifMi = true,
                            Baslik = "Merkezde yol düzenleme çalışması",
                            Icerik = "Atatürk Caddesi çevresinde şerit daraltma uygulanacaktır. Sürücülerin alternatif güzergâhları kullanması rica olunur.",
                            KapsamYaricapiMetre = 6000,
                            Kategori = "YolCalismasi",
                            KonumBoylam = 35.325000000000003,
                            KonumEnlem = 37.005000000000003,
                            Oncelik = "Bilgi",
                            YayinBaslangicTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YayinBitisTarihi = new DateTime(2030, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AktifMi = true,
                            Baslik = "Hafta sonu kültür etkinlikleri",
                            Icerik = "Belediye kültür merkezlerinde hafta sonu çocuk atölyeleri ve açık hava gösterileri düzenlenecektir.",
                            KapsamYaricapiMetre = 0,
                            Kategori = "Etkinlik",
                            Oncelik = "Bilgi",
                            YayinBaslangicTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YayinBitisTarihi = new DateTime(2030, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AkilliSehir.Core.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CalistigiBirim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParolaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TcKimlikNoHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TelefonNumarasi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.HasIndex("TcKimlikNoHash")
                        .IsUnique()
                        .HasFilter("[TcKimlikNoHash] IS NOT NULL");

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("AkilliSehir.Core.Entities.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("TarihSaat")
                        .HasColumnType("datetime2");

                    b.Property<int>("VatandasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VatandasId", "TarihSaat");

                    b.HasIndex("Birim", "TarihSaat", "Durum");

                    b.ToTable("Randevular", (string)null);
                });

            modelBuilder.Entity("AkilliSehir.Core.Entities.Ariza", b =>
                {
                    b.HasOne("AkilliSehir.Core.Entities.Kullanici", "AtananPersonel")
                        .WithMany("AtananArizalar")
                        .HasForeignKey("AtananPersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AkilliSehir.Core.Entities.Kullanici", "BildirimiYapanVatandas")
                        .WithMany("BildirilenArizalar")
                        .HasForeignKey("BildirimiYapanVatandasId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AtananPersonel");

                    b.Navigation("BildirimiYapanVatandas");
                });

            modelBuilder.Entity("AkilliSehir.Core.Entities.Randevu", b =>
                {
                    b.HasOne("AkilliSehir.Core.Entities.Kullanici", "Vatandas")
                        .WithMany("Randevular")
                        .HasForeignKey("VatandasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vatandas");
                });

            modelBuilder.Entity("AkilliSehir.Core.Entities.Kullanici", b =>
                {
                    b.Navigation("AtananArizalar");

                    b.Navigation("BildirilenArizalar");

                    b.Navigation("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
